jwt:
  secret: a-zA-Z0-9._^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$

server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/wflow}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
  #change-log: classpath:db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher

  web:
    locale: ru
    resources:
      add-mappings: false

  mail:
    host: mail.wflow-app.ru
    port: 587
    username: service@wflow.ru
    password: Fe8de1YnY1Q1y8In
    properties.mail.smtp:
      auth: true
      starttls.enable: true
    send-greeting: true

springdoc:
  swagger-ui:
    path: /test/swagger-ui-custom.html
    operationsSorter: method

source:
  service:
    email: "messages.service.email.messages"
    auth: "messages.auth.messages"
    notification: "messages.notification.messages"
  main: "main"

job:
  cron:
    resendEmail: "0 0/5 * ? * *"

uploadcare:
  scheme: "Uploadcare.Simple"
  public-key: "0023b247fac8f6e0fb7e"
  secret-key: "e1fbbc8edb0974a81353"

app:
  saveImageInDb: true